name: Auto Deploy

on:
  workflow_run:
    workflows: [📦 Build and Release]
    types: [completed]
    branches: [develop, main]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "${{ github.event.workflow_run.id }} workflow passed"

  deploy-dev:
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Deploying it to dev'

  deploy-qa:
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Deploying it to qa'
