name: Auto Deploy

on:
  workflow_run:
    workflows: [📦 Build and Release]
    types: [completed]
    branches: [develop, main]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    steps:
      - run: echo Deployment triggered by ${{ github.event.workflow_run.id || github.actor }}

  deploy-dev:
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Deploying it to dev'

  deploy-qa:
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Deploying it to qa'
