name: Auto Deploy

on:
  workflow_run:
    workflows: [📦 Build and Release]
    types: [completed]
    branches: [develop, main]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    steps:
      - run: echo Deployment triggered by ${{ github.event.workflow_run.id || github.actor }}

  dev:
    needs: [check]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "dev"
      release: "develop"

  staging:
    needs: [check]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ github.job }}
