name: 📦 Build and Release

on:
  push:
  workflow_dispatch:
    inputs:
      fail:
        description: Force fail?
        type: boolean
        required: true
        default: false

env:
  CHECKOUT: actions/checkout@v3

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Exiting
        run: |
          [[ "${{ github.event.inputs.fail }}" == "true" ]] && exit 1 || exit 0

  foo:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.job }}
      - uses: ${{ env.CHECKOUT }}
        with:
          ref: ${{ github.ref }}

  bar:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.job }}

  baz:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.job }}
      - run: gh workflow list
