name: 📦 Build and Release

on:
  push:
  workflow_dispatch:
    inputs:
      fail:
        description: Force fail?
        type: boolean
        required: true
        default: false

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Exiting
        run: |
          [[ "${{ github.event.inputs.fail }}" == "true" ]] && exit 1 || exit 0

  foo: &template_job
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.job }}

  bar:
    <<: *template_job

  baz:
    <<: *template_job
