name: Deploy!

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Pick a env
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

      release:
        description: "Enter a release version"
        required: false

  workflow_call:
    inputs:
      environment:
        description: Pick a env
        required: false
        type: string
        default: "dev"

      release:
        description: "Enter a release version"
        type: string
        required: false
        default: "latest"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to ${{ inputs.environment }}
        run: echo Look ma! I am deploying ${{inputs.release}} to ${{ inputs.environment }}!
